CREATE TABLE User (
    id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Catalog (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    createdBy INT NOT NULL,
    updatedBy INT DEFAULT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (createdBy) REFERENCES User(id),
    FOREIGN KEY (updatedBy) REFERENCES User(id)
);

CREATE TABLE Category (
    id INT PRIMARY KEY AUTO_INCREMENT,
    catalogId INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    createdBy INT NOT NULL,
    updatedBy INT DEFAULT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (catalogId) REFERENCES Catalog(id) ON DELETE CASCADE,
    FOREIGN KEY (createdBy) REFERENCES User(id),
    FOREIGN KEY (updatedBy) REFERENCES User(id)
);

CREATE TABLE CategoryField (
    id INT PRIMARY KEY AUTO_INCREMENT,
    categoryId INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    dataType ENUM('text', 'number', 'date', 'image', 'sound') NOT NULL,
    createdBy INT NOT NULL,
    updatedBy INT DEFAULT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (categoryId) REFERENCES Category(id) ON DELETE CASCADE,
    FOREIGN KEY (createdBy) REFERENCES User(id),
    FOREIGN KEY (updatedBy) REFERENCES User(id)
);

CREATE TABLE Item (
    id INT PRIMARY KEY AUTO_INCREMENT,
    categoryId INT NOT NULL,
    name VARCHAR(255),
    createdBy INT NOT NULL,
    updatedBy INT DEFAULT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (categoryId) REFERENCES Category(id) ON DELETE CASCADE,
    FOREIGN KEY (createdBy) REFERENCES User(id),
    FOREIGN KEY (updatedBy) REFERENCES User(id)
);

CREATE TABLE ItemField (
    id INT PRIMARY KEY AUTO_INCREMENT,
    itemId INT NOT NULL,
    categoryFieldId INT NOT NULL,
    value TEXT NOT NULL,
    createdBy INT NOT NULL,
    updatedBy INT DEFAULT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (itemId) REFERENCES Item(id) ON DELETE CASCADE,
    FOREIGN KEY (categoryFieldId) REFERENCES CategoryField(id) ON DELETE CASCADE,
    FOREIGN KEY (createdBy) REFERENCES User(id),
    FOREIGN KEY (updatedBy) REFERENCES User(id)
);

